# Site settings
title: "bourbonify-jekyll"
email: your-email@domain.com
description: "Simple boilerplate for quickly setting up Jekyll with Normalize, Bourbon and Neat."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

exclude: ['node_modules', 'package.json', 'gulpfile.js', '.bowerrc', 'bower.json', 'assets', 'LICENSE', 'README.md', 'bower_components'] # recommended not to remove anything from this line
